// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router';

// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as LayoutImport } from './routes/_layout';

// Create Virtual Routes

const LayoutIndexLazyImport = createFileRoute('/_layout/')();
const LayoutCartIndexLazyImport = createFileRoute('/_layout/cart/')();
const LayoutProductsProductIdIndexLazyImport = createFileRoute('/_layout/products/$productId/')();

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute
} as any);

const LayoutIndexLazyRoute = LayoutIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute
} as any).lazy(() => import('./routes/_layout/index.lazy').then((d) => d.Route));

const LayoutCartIndexLazyRoute = LayoutCartIndexLazyImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => LayoutRoute
} as any).lazy(() => import('./routes/_layout/cart/index.lazy').then((d) => d.Route));

const LayoutProductsProductIdIndexLazyRoute = LayoutProductsProductIdIndexLazyImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => LayoutRoute
} as any).lazy(() =>
  import('./routes/_layout/products/$productId/index.lazy').then((d) => d.Route)
);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof LayoutImport;
      parentRoute: typeof rootRoute;
    };
    '/_layout/': {
      id: '/_layout/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof LayoutIndexLazyImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/cart/': {
      id: '/_layout/cart/';
      path: '/cart';
      fullPath: '/cart';
      preLoaderRoute: typeof LayoutCartIndexLazyImport;
      parentRoute: typeof LayoutImport;
    };
    '/_layout/products/$productId/': {
      id: '/_layout/products/$productId/';
      path: '/products/$productId';
      fullPath: '/products/$productId';
      preLoaderRoute: typeof LayoutProductsProductIdIndexLazyImport;
      parentRoute: typeof LayoutImport;
    };
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexLazyRoute: typeof LayoutIndexLazyRoute;
  LayoutCartIndexLazyRoute: typeof LayoutCartIndexLazyRoute;
  LayoutProductsProductIdIndexLazyRoute: typeof LayoutProductsProductIdIndexLazyRoute;
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexLazyRoute,
  LayoutCartIndexLazyRoute,
  LayoutProductsProductIdIndexLazyRoute
};

const LayoutRouteWithChildren = LayoutRoute._addFileChildren(LayoutRouteChildren);

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren;
  '/': typeof LayoutIndexLazyRoute;
  '/cart': typeof LayoutCartIndexLazyRoute;
  '/products/$productId': typeof LayoutProductsProductIdIndexLazyRoute;
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexLazyRoute;
  '/cart': typeof LayoutCartIndexLazyRoute;
  '/products/$productId': typeof LayoutProductsProductIdIndexLazyRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  '/_layout': typeof LayoutRouteWithChildren;
  '/_layout/': typeof LayoutIndexLazyRoute;
  '/_layout/cart/': typeof LayoutCartIndexLazyRoute;
  '/_layout/products/$productId/': typeof LayoutProductsProductIdIndexLazyRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '' | '/' | '/cart' | '/products/$productId';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/cart' | '/products/$productId';
  id: '__root__' | '/_layout' | '/_layout/' | '/_layout/cart/' | '/_layout/products/$productId/';
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/cart/",
        "/_layout/products/$productId/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/cart/": {
      "filePath": "_layout/cart/index.lazy.tsx",
      "parent": "/_layout"
    },
    "/_layout/products/$productId/": {
      "filePath": "_layout/products/$productId/index.lazy.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
